# Generated by Django 4.1.9 on 2023-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
